### ISSUE TITLE
Compatability with php-parser 3.0

### ISSUE THREAD

**Issue by nekosaur** [chris-l/php-unparser#17]
It looks like there are some breaking changes in the coming php-parser 3.0 that results in php-unparser being unable to use its output to unparse. Specifically I had problems with simple string arrays.

```php
<?

return [
  "xzczxc",
  "qweqweqwe"
];
```

```
Node: xzczxc
Node kind: undefined
{ Error: Bad AST structure
    at CodeGen.process (/home/vagrant/apps/translation-scripts/node_modules/php-unparser/node_translators/index.js:42:13)
    at /home/vagrant/apps/translation-scripts/node_modules/php-unparser/node_translators/array.js:11:19
    at Array.map (<anonymous>)
    at CodeGen.module.exports [as array] (/home/vagrant/apps/translation-scripts/node_modules/php-unparser/node_translators/array.js:19:25)
    at CodeGen.process (/home/vagrant/apps/translation-scripts/node_modules/php-unparser/node_translators/index.js:32:31)
    at /home/vagrant/apps/translation-scripts/node_modules/php-unparser/node_translators/array.js:11:19
    at Array.map (<anonymous>)
    at CodeGen.module.exports [as array] (/home/vagrant/apps/translation-scripts/node_modules/php-unparser/node_translators/array.js:19:25)
    at CodeGen.process (/home/vagrant/apps/translation-scripts/node_modules/php-unparser/node_translators/index.js:32:31)
    at CodeGen.module.exports [as return] (/home/vagrant/apps/translation-scripts/node_modules/php-unparser/node_translators/return.js:12:22) node: 'xzczxc' }
```

**Comment by chris-l** [comment]
Well, yes. I haven't seen the new parser yet, but for what @ichiriac said on his issues, it seemed like the changes he was planning to do would completely break the unparser on its current state.

**Comment by ichiriac** [comment]
Hi, yes actually v3 will not be backward compatible, but changes should be enough simple to implement. Remains some changes to implement before the v3 will be fully released and then I'll write a migration guide and send a PR on this project.
