### ISSUE TITLE
Bad AST structure, expects array

### ISSUE THREAD

**Issue by b4dnewz** [chris-l/php-unparser#9]
The example from the documentation throws this error:
```
var unparse = require('php-unparser');
var ast = {
  "kind": "program",
  "children": [
    {
      "kind": "echo",
      "arguments": [
        {
          "kind": "string",
          "value": "hello world",
          "isDoubleQuote": true
        }
      ]
    }
  ],
  "errors": []
};

console.log(unparse(ast));
```
```
Error: Bad AST structure, expects array
    at CodeGen.process (C:\Users\winflop\Desktop\test\php-parse\node_modules\php-unparser\node_translators\index.js:34:11)
    at module.exports (C:\Users\winflop\Desktop\test\php-parse\node_modules\php-unparser\index.js:14:18)
```

**Comment by b4dnewz** [comment]
actually I was using a old version of the package, that one in php-writer from glayzzle/php-writer
